version: "3.8"
services:
  mqtt:
    image: eclipse-mosquitto:1.6.12
    ports:
      - 1883:1883
    volumes:
      - ${PWD}/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ${PWD}/mosquitto/log:/mosquitto/log:rw
      - ${PWD}/mosquitto/data:/mosquitto/data:rw